/**
 * Notion Integration
 * Syncs application tracker to Notion database
 */

export interface NotionApplication {
  company: string;
  role: string;
  matchScore: number;
  status: string;
  lastAction: string;
  nextFollowUp: string;
  notes: string;
  url?: string;
}

/**
 * Mock Notion database for demo
 */
let mockNotionDatabase: NotionApplication[] = [];

/**
 * Check if Notion is actually connected (real API integration)
 */
export function isNotionConnected(): boolean {
  // Check for real Notion API credentials
  const notionToken = process.env.NOTION_API_KEY;
  const notionDatabaseId = process.env.NOTION_DATABASE_ID;

  return !!(notionToken && notionDatabaseId);
}

/**
 * Create or update Notion entries for recommended jobs
 */
export async function syncToNotion(
  jobs: Array<{
    company: string;
    title: string;
    score: number;
    url?: string;
  }>
): Promise<{ success: boolean; synced: number; entries: NotionApplication[]; demoMode: boolean }> {
  const demoMode = !isNotionConnected();

  if (demoMode) {
    console.log('⚠️ Notion running in DEMO MODE (no real API connection)');
  }

  // TODO: Integrate with Notion API
  // For now, simulate sync

  const entries: NotionApplication[] = [];

  for (const job of jobs) {
    const entry: NotionApplication = {
      company: job.company,
      role: job.title,
      matchScore: job.score,
      status: 'To Apply',
      lastAction: new Date().toISOString().split('T')[0],
      nextFollowUp: getNextFollowUpDate(3), // 3 days later
      notes: `Auto-generated by Autonomous Internship Agent. Match score: ${job.score}%`,
      url: job.url,
    };

    entries.push(entry);
    mockNotionDatabase.push(entry);
  }

  if (demoMode) {
    console.log(`✅ Synced ${entries.length} jobs to Notion (DEMO MODE - simulated)`);
  } else {
    console.log(`✅ Synced ${entries.length} jobs to Notion`);
  }

  return {
    success: true,
    synced: entries.length,
    entries,
    demoMode,
  };
}

/**
 * Update application status in Notion
 */
export async function updateNotionStatus(
  company: string,
  status: string,
  notes?: string
): Promise<{ success: boolean }> {
  // Find entry in mock database
  const entry = mockNotionDatabase.find(e => e.company === company);

  if (entry) {
    entry.status = status;
    entry.lastAction = new Date().toISOString().split('T')[0];
    if (notes) {
      entry.notes += `\n${notes}`;
    }
    console.log(`✅ Updated ${company} status to ${status} in Notion (mock)`);
    return { success: true };
  }

  console.warn(`⚠️ Company ${company} not found in Notion database`);
  return { success: false };
}

/**
 * Get all applications from Notion
 */
export async function getNotionApplications(): Promise<NotionApplication[]> {
  return [...mockNotionDatabase];
}

/**
 * Calculate next follow-up date
 */
function getNextFollowUpDate(daysFromNow: number): string {
  const date = new Date();
  date.setDate(date.getDate() + daysFromNow);
  return date.toISOString().split('T')[0];
}

/**
 * Batch update statuses based on email signals
 */
export async function batchUpdateFromEmails(
  statusMap: Record<string, string>
): Promise<{ updated: number }> {
  let updated = 0;

  for (const [company, status] of Object.entries(statusMap)) {
    const result = await updateNotionStatus(company, status, 'Status updated from email');
    if (result.success) {
      updated++;
    }
  }

  return { updated };
}

/**
 * Generate Notion database statistics
 */
export function getNotionStats(): {
  total: number;
  byStatus: Record<string, number>;
} {
  const byStatus: Record<string, number> = {};

  for (const entry of mockNotionDatabase) {
    byStatus[entry.status] = (byStatus[entry.status] || 0) + 1;
  }

  return {
    total: mockNotionDatabase.length,
    byStatus,
  };
}
